#ifndef TURTLEINTERPRET_H_
#define TURTLEINTERPRET_H_

#include "abstractinterpret.h"
#include "lsgeode.h"

namespace AP_LSystem {
/**
  * This class interprets a word generated by L-system word generator. It creates a geometry using turtle
  * graphics.
  */
class TurtleInterpret : public AbstractInterpret
{
private:
	
public:
    /**
      * Creates a turtle interpret. This interpret has to be connected to scene graph. During interpretation
      * It generates a geometry stored in LSGeode instances.
      * @param owner parent in scene graph
      */
	TurtleInterpret( osg::Group * owner );

	~TurtleInterpret(void);

    /**
      * Interpretes a word by converting L-system modules to turtle commands.
      * @param word interpreted word
      * @return error code
      */
    virtual int parse( ParseableString * word );
};
}

#endif
